# Generated by Django 4.0.6 on 2022-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='FormText',
        ),
        migrations.DeleteModel(
            name='FormTitle',
        ),
    ]
